name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows app
      run: flutter build windows --release

    - name: Create Windows artifact
      run: |
        Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath "jigsaw_puzzle_windows.zip"

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: jigsaw_puzzle_windows.zip

  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release --split-per-abi

    - name: Upload Android artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: build/app/outputs/flutter-apk/*.apk

  create-release:
    needs: [build-windows, build-android]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-release
        path: ./artifacts

    - name: Download Android artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release
        path: ./artifacts

    - name: Get version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=dev-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Jigsaw Puzzle ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          ## Jigsaw Puzzle Release ${{ steps.get_version.outputs.VERSION }}
          
          ### Downloads
          - **Windows**: Download `jigsaw_puzzle_windows.zip` and extract it
          - **Android**: Choose the appropriate APK for your device architecture:
            - `app-arm64-v8a-release.apk` - For most modern Android devices (64-bit ARM)
            - `app-armeabi-v7a-release.apk` - For older Android devices (32-bit ARM)
            - `app-x86_64-release.apk` - For Android emulators or x86_64 devices
          
          ### Installation
          - **Windows**: Extract the zip file and run `jigsaw_puzzle.exe`
          - **Android**: Enable "Install from unknown sources" in your device settings, then install the appropriate APK file
          
          ### What's New
          - Bug fixes and performance improvements
          - Updated Flutter framework

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/jigsaw_puzzle_windows.zip
        asset_name: jigsaw_puzzle_windows.zip
        asset_content_type: application/zip

    - name: Upload Android APK (arm64-v8a)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/app-arm64-v8a-release.apk
        asset_name: jigsaw_puzzle_android_arm64-v8a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Android APK (armeabi-v7a)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/app-armeabi-v7a-release.apk
        asset_name: jigsaw_puzzle_android_armeabi-v7a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Android APK (x86_64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/app-x86_64-release.apk
        asset_name: jigsaw_puzzle_android_x86_64.apk
        asset_content_type: application/vnd.android.package-archive
